### ISSUE TITLE
Missing breakpoints (can happen locally, happens with VSCode SSH and much more visible with GitPod)

### ISSUE THREAD

**Issue by jgueytat** [WebFreak001/code-debug#260]
Hi,

I can not hit any breakpoint with the extension on GitPod. I'll try to give some more information soon.

**Comment by jgueytat** [comment]
### With the code or Theia IDE on GitPod
![Native_Debug_on_GitPod](https://user-images.githubusercontent.com/1152718/111082822-8d328e80-850a-11eb-9a2a-9e3f3429f102.png)

The breakpoint is not taken into account.

**Comment by jgueytat** [comment]
```sh
$ gdb --version
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
```

**Comment by jgueytat** [comment]
**Link to check bellow :**

[![Gitpod ready-to-code](https://img.shields.io/badge/Gitpod-ready--to--code-blue?logo=gitpod)](https://gitpod.io/#https://bitbucket.org/jgueytat/helloworld_in_ada/src/master/)

**Comment by WebFreak001** [comment]
did you compile your program in debug mode? did you try running it just in the console once to see if breakpoints hit?

The gitpod links needs authorization through Bitbucket, which I don't have.

**Comment by jgueytat** [comment]
My point is to get the **exact same configuration** working on **VSCode**, **VSCode Remote** and **GitPod** without having to switch between extensions.

Right now, VSCode and VSCode Remote Container work both even if the Debug Console output slightly differ.

I made a fork available on Github : https://github.com/jgueytat/HelloWorld-in-Ada available on GitPod with the following link http://gitpod.io/#https://github.com/jgueytat/HelloWorld-in-Ada .

I was able to get a breakpoint with the extension https://github.com/eclipse-cdt/cdt-gdb-vscode. But their plugin is not available on the VSCode plugin registry. Also your extension is more mature.

Also, it is possible in the GitPod settings to enable the extra features to check if it's getting better with code instead of Theia.

**Comment by GitMensch** [comment]
Just to not leave a wrong note like that here ;-) https://open-vsx.org/extension/eclipse-cdt/cdt-gdb-vscode - and if it works with that extension in GitPod it also should work with native-debug.

... just tested and everything seems to work. That's what I've done:

* removed the allowBreakpointsAnywhere user setting (should not be needed)
* run the build task
* set a breakpoint
* run "launch"

done:

![running in debug](https://user-images.githubusercontent.com/6699539/111364329-618de080-8691-11eb-9726-d22240501768.png)

Did I miss something or can we close this issue?

**Comment by jgueytat** [comment]
Yes you missed the **exact same configuration** part which means to be able to get the same output with this extension.
As far as I know the extension cdt-gdb-vscode is not available on the VSCode market.

**Comment by GitMensch** [comment]
I've just opened your gitpod io and found it works - so was the gitpod.io link wrong?

... also on your gitpod.io link:

![extension](https://user-images.githubusercontent.com/6699539/111365274-98b0c180-8692-11eb-8200-140fb510df42.png)

**Comment by jgueytat** [comment]
Here is the running workspace : https://red-reptile-u4ec8jxr.ws-eu03.gitpod.io/
I would be glad to have it working too! I removed the settings also.

**Comment by GitMensch** [comment]
It is exactly the same for me with this workspace:

* clicked the link
* used Terminal->Run build task
* set a breakpoint
* switched to the debugging view
* clicked on Launch Program

Program stops on the breakpoint exactly like in the screenshot above...

**Comment by jgueytat** [comment]
### VSCode : 
![VSCode_OK](https://user-images.githubusercontent.com/1152718/111371934-51c6ca00-869a-11eb-9cb8-a3d9a2fd2941.png)
### VSCode Remote : 
![VSCode_Remote_OK](https://user-images.githubusercontent.com/1152718/111371941-53908d80-869a-11eb-86a6-83b435f469c7.png)
### GitPod : 
![GitPod_KO](https://user-images.githubusercontent.com/1152718/111371961-59866e80-869a-11eb-8e6b-e80b81568867.png)

I removed all previous Docker images, removed my "Enable Next Features" option from GitPod and added two output debug lines to see if I can get a breakpoint in between or not.

**Comment by jgueytat** [comment]
![GitPod_KO_GDB_OK](https://user-images.githubusercontent.com/1152718/111372740-52ac2b80-869b-11eb-956b-682bdcc5e959.png)

I should find a way to get more debug output.

**Comment by GitMensch** [comment]
> I should find a way to get more debug output.

Use the launch config option showDevOuput (or similar named).

As noted: it just worked out-of the box for me when using your previous gitpod.io (currently access is not permitted, otherwise I'd try [the exact same steps as given above] a third time).

**Comment by jgueytat** [comment]
### GitPod output :
![showDevDebugOutput-GitPod](https://user-images.githubusercontent.com/1152718/111386500-a2472300-86ac-11eb-9369-0a69b7f8172a.png)
### VSCode output :
![showDevDebugOutput-VSCodeRemote](https://user-images.githubusercontent.com/1152718/111386519-a5daaa00-86ac-11eb-8bac-413e2e6c33ec.png)

**Comment by jgueytat** [comment]
I'll keep this workspace https://gray-wasp-3ie8v2ys.ws-eu03.gitpod.io/ running for some times.

**Comment by jgueytat** [comment]
Some help from Gitpod guys ! https://github.com/gitpod-io/gitpod/issues/3470

**Comment by jgueytat** [comment]
The troubles does not come from GitPod as I can reproduce it locally with VSCode directly.

![VSCode-MissingBreakpoint](https://user-images.githubusercontent.com/1152718/111457666-cc362f00-8718-11eb-95b8-6c66dcd1005b.png)
![VSCode-MissingBreakpoint-2](https://user-images.githubusercontent.com/1152718/111457676-cdfff280-8718-11eb-83ad-a34e4ffd4901.png)

![VSCode-NOT-MissingBreakpoint](https://user-images.githubusercontent.com/1152718/111457684-d1937980-8718-11eb-800c-0f877a3eb26a.png)
![VSCode-NOT-MissingBreakpoint-2](https://user-images.githubusercontent.com/1152718/111457695-d3f5d380-8718-11eb-8076-d6e05050ee13.png)

**Comment by GitMensch** [comment]
> The troubles does not come from GitPod as I can reproduce it locally with VSCode directly.

And what is the difference between "working" and "not working" now that leads to "setting breakpoints work" (or not)?

**Comment by jgueytat** [comment]
> > The troubles does not come from GitPod as I can reproduce it locally with VSCode directly.
> 
> And what is the difference between "working" and "not working" now that leads to "setting breakpoints work" (or not)?

Yes I updated the title of the issue. The point is to be able to be sure to have set all the breakpoints before running the application.

**Comment by jgueytat** [comment]
Here is another setup for C/C++ in which the breakpoints can't get reach. It's easily reproductible on GitPod.
https://github.com/jgueytat/HelloWorld-in-C
https://aqua-porpoise-5o327cb5.ws-eu03.gitpod.io/

**Comment by GitMensch** [comment]
Thanks for the update. Can you please provide the reproducers as a zipped workspace containing the necessary sources, settings, ...?

**Comment by jgueytat** [comment]
Yes ! Because I keep updating my worskapces. I'll do that !

**Comment by jgueytat** [comment]
The download option is broken right now.

**Comment by jgueytat** [comment]
I do not play with the two workspaces anymore. I won't make much commits for some times neither. You can still create a fresh workspace with https://gitpod.io/#https://github.com/jgueytat/HelloWorld-in-C or https://gitpod.io/#https://github.com/jgueytat/HelloWorld-in-Ada.

I'm pretty sure you can get the same behavior by launching the debug 2/3 times. It happens also for me to get the first one working. I'll provide an archive as soon as the functionnality is available again.

**Comment by jgueytat** [comment]
I just tried out VSCode WSL. Now I have C/C++ and Ada projects working like a charm locally with VSCode WSL and VSCode Container. I can **hit breakpoints mostly all the time locally**, and **mostly never on GitPod**.
I think there help might be interesting.

**Comment by jgueytat** [comment]
I can reproduce the bug with **VSCode SSH** with the exact same workflow. I miss less breakpoints than on GitPod but it's **quite reproducable without GitPod** at all. I guess there is something missing to wait for the already set breakpoints at launch.

**Comment by jgueytat** [comment]
This project has really nothing special. The point is only to launch the debugger some times in a row with GitPod or VSCode SSH. I hope you will find it out @GitMensch. A common set of extensions would really help.

[HelloWorld-in-C-master.zip](https://github.com/WebFreak001/code-debug/files/6186030/HelloWorld-in-C-master.zip)

**Comment by jgueytat** [comment]
> did you compile your program in debug mode? did you try running it just in the console through normal gdb once to see if breakpoints hit?
> 
> The gitpod links needs authorization through Bitbucket, which I don't have.

@WebFreak001, I can now confirm the extension is missing breakpoints at launch. This is much more visible on GitPod even if I was able to reproduce the issue with VSCode SSH. Trying any small project and running a few times the debug will make it visible.

**Comment by WebFreak001** [comment]
I haven't read too much of this, but this sounds like it could be a race condition with the extension starting the program and then adding breakpoints while it's running, but the program already being ran over them?

**Comment by jgueytat** [comment]
Hi @WebFreak001 I tried to add getchar() to get some time for the breakpoints to get set and... I found another bug. There is no way to wait for the user input. https://github.com/gitpod-io/gitpod/issues/3566

If I start a launch with the breakpoint already set, I will miss the breakpoint.
I was expecting to get some time with the getchar().

**eclipse-cdt.cdt-gdb-vscode** has also an issue with the user input.

**Comment by jgueytat** [comment]
Recent GitPod Workspace : https://coral-puffin-q8gr472u.ws-eu17.gitpod.io
![image](https://user-images.githubusercontent.com/1152718/143860836-81f6ea6e-0d82-492a-890b-26126c122337.png)

**Comment by GitMensch** [comment]
Rechecked on GitPod with the use of the given zip and a compile with `mkdir -p ./build && g++ -g -o ./build/hello main.cpp` - works like a charm now, so I'm closing it. @jgueytat It would still be nice if you could check with your other projects.
